version: "3.7"

services:
  irida_web:
    restart: always
    build:
      context: ./docker-svc/irida
      dockerfile: Dockerfile
    container_name: irida_web
    depends_on:
      - irida_mysql
    ports:
      - "8080:8080"
    volumes:
      - irida_web_data:/data/irida

  irida_mysql:
    restart: always
    image: mysql:8.0
    container_name: irida_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
      MYSQL_DATABASE: irida_db
      MYSQL_USER: irida_user
      MYSQL_PASSWORD: irida_passwd
    command: mysqld --sql_mode=""
    volumes:
      - irida_mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE


  irida_galaxy:
    restart: always
    build:
      context: ./docker-svc/galaxy
      dockerfile: Dockerfile
    container_name: irida_galaxy
    environment:
      GALAXY_CONFIG_BRAND: "COMBAT-TB Workbench"
      GALAXY_LOGGING: full
    volumes:
      - irida_web_data:/data/irida
      - irida_galaxy_data:/export
    ports:
      - "9090:80"
      - "21:21"
      - "8800:8800"
      - "9002:9002"
volumes:
  irida_mysql_data:
  irida_web_data:
  irida_galaxy_data:
