version: '2'

services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: iridanginx
    network_mode: "bridge"
    ports:
      - "80:80"
    links:
      - iridaweb
  iridadb:
    image: mysql:5.7.18
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    command: mysqld --sql_mode=""
    network_mode: "bridge"
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
      MYSQL_DATABASE: irida_db
      MYSQL_USER: irida_user
      MYSQL_PASSWORD: irida_passwd

  iridaweb:
    depends_on:
      - iridadb
    links:
      - iridadb
    build: .
    image: iridaweb
    network_mode: "bridge"
    ports:
      - "8080:8080"
    volumes:
      - data_volume:/data  
    restart: always

# https://docs.openstack.org/project-deploy-guide/kolla-ansible/ocata/quickstart.html#build-container-images
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 2450

volumes:
  db_data:
  data_volume:

