- name: Include variables.
  include_vars: 
    file: "vars/all.yml"
    name: all

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Install a list of packages
  apt:
    name: "{{ packages }}"  

- name: Creates irida home dir
  file:
    path: /etc/irida
    state: directory

- name: Clean the apt list PATH
  file:
    state: absent
    path: "{{ apt_list_path }}" 
 
- name: Install dependencies 
  command: "{{item}}"
  with_items:
    - set -ex
    - dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"
	  - wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/{{ gosu_version }}/gosu-$dpkgArch"
	  - wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/{{ gosu_version }}/gosu-$dpkgArch.asc"
	  - export GNUPGHOME="$(mktemp -d)"
	  - gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
	  - gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu
	  - rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc
	  - chmod +x /usr/local/bin/gosu
    - gosu nobody true
    

- name: Creates Irida data dir
  file:
    path: "{{irida_data_dir}}"/data
    state: directory

- name: Download IRIDA war file
  get_url:
    url: https://github.com/SANBI-SA/irida/releases/download/sanbi-bvc-test/irida-0.17.1.war
    dest: /usr/local/tomcat/webapps/irida.war

- name: Creates IRIDA Data subdirectories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{irida_data_dir}}"/sequence
    - "{{irida_data_dir}}"/reference
    - "{{irida_data_dir}}"/output

- name: Setting variables for JAVA_OPTS
  shell: "echo $JAVA_OPTS"
  environment:
    JAVA_OPTS: -Dspring.profiles.active=prod -Ddandelion.profile.active=prod
  register: javaopts
  - debug:
      var: javaopts.stdout

- name: Setting variables for GALAXY admin user
  shell: "echo $GALAXY_ADMIN_USER"
  environment:
    GALAXY_ADMIN_USER: zipho@sanbi.ac.za
  register: gxadminuser
  - debug:
      var: gxadminuser.stdout

- name: Setting variables for IRIDA StartUp
  shell: "echo $IRIDA_VERSION"
  environment:
    IRIDA_VERSION: "{{irida_version}}"
    IRIDA_DATA_DIR: "{{ irida_data_dir}}"
  register: irida_startup
  - debug:
      var: irida_startup.stdout

- name: install WEB configuration
  template:
    src: web.conf.j2
    dest: /etc/irida/web.conf
  
- name: install IRIDA configuration
  template:
    src: irida.conf.j2
    dest: /etc/irida/irida.conf

- name: install Start-Up configuration script
  template:
    src: wait-for-it.sh.j2
    dest: "{{ irida_home_dir}}"/wait-for-it.sh

- name: Transfer the startup script
    copy: src=startup.sh dest="{{ irida_home}}" mode=0777

- name: Execute the startup script
    command: sh "{{ irida_home}}"/startup.sh