---
- name: Install IRIDA on Cluster server
  hosts: demoservers
  tags: irida-demo
  become: yes
  pre_tasks:
    - include_role:
        name: ansible-role-cephfs_client        
      vars:
        cephfs_client_mapping:
          - {"src": "/projects/irida-dev", "dst": "/irida-dev", "id": "irida-dev", "key": "AQBccmVcKxj2JBAAAZ5kD/cgucYaWEsZFJ/pEA=="}
          - {"src": "/projects/irida", "dst": "/irida", "id": "irida", "key": "AQBRcmVckrrBDxAAw3fqpifPXO59NZwvVVWouA=="}
          - {"src": "/projects/galaxy-dev", "dst": "/galaxy-dev", "id": "galaxy-dev", "key":"AQCgAU9c0dV5IhAAs9CZGvBSo9LFX3yqF6xJzQ=="}
          - {"src": "/projects/galaxy", "dst": "/galaxy", "id": "galaxy", "key": "AQCUFlBcowFeKBAAbdPKa5+ojFyQJgX9YY/WLw===="}
  tasks:
    - name: Create Mysql user and database
      include_role:
        name: ansible-role-mysql 
    
    - name: Install Java8
      include_role:
        name: geerlingguy.java

    - name: Install Tomcat8
      include_role:
        name: flxpeters.tomcat8
  
    - name: Install IRIDA
      include_role:
        name: sanbi.irida
