apt_list_path:
  - /var/lib/apt/lists
packages:
  - perl
  - fastqc
  - ca-certificates
  - python-pymysql
gosu_version: "1.10"
irida_user: ubuntu
irida_data_dir: "/irida/data"
irida_home_dir: "/home/ubuntu/"
irida_version: 0.17.1
irida_tomcat_home: "/opt/tomcat/current"
mysql_user: irida_user
mysql_password: irida_passwd
mysql_database: irida_db
mysql_url: localhost
mysql_port: 3306
tomcat_daemon: tomcat
galaxy_execution_email: "irida@sanbi.ac.za"
galaxy_execution_url: "http://galaxy.sanbi.ac.za"
galaxy_execution_apikey: GALAXY_API_KEY
